providers:
  docker:
    endpoint: "tcp://docker-socket-proxy:2375"
    exposedByDefault: false
    defaultRule: ""

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"

log:
  level: INFO
